project:
  type: website
  output-dir: docs

website:
  title: "Excursiones SEBOTA"
  sidebar:
    background: primary
    logo: "SEBOTA_logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://se-bota.github.io/sebota/
        text: Inicio
    style: docked
    contents:
      - href: I-edicion.qmd
        text: Segunda edición-Cazorla 2024
      - href: II-edicion.qmd
        text: Primera edición-Somiedo 2023



format:
  html:
    theme: minty
    # css: styles.css
    toc: true

execute:
  freeze: auto

